export const languages = {
  en: "English",
  es: "Español",
  pt: "Português",
};

export const defaultLang = "en";

export const ui = {
  en: {
    nav: {
      philosophy: "Philosophy",
      services: "Services",
      process: "Our Process",
      faq: "FAQ",
      cta: "Contact Us",
    },
    hero: {
      title: {
        prefix: "We Drive ",
        highlight: "Your Growth",
        suffix: " with Custom Development & Digital Marketing",
      },
      subtitle:
        "We build the custom software solutions and marketing strategies your business needs to scale and succeed in today's market.",
      ctaButton: "Let's Discuss Your Project",
    },
    showcase: {
      title_prefix: "Our ",
      title_highlight: "Work",
      items: [
        {
          title: "High-Performance E-commerce",
          description:
            "An ultra-fast online store built with Astro, featuring zero client-side JavaScript by default for instant loading and impeccable SEO.",
          imageUrl:
            "https://ix-marketing.imgix.net/case-study_tile_bentobox.png?auto=format,compress&w=1446",
          projectUrl: "#",
          tags: ["Astro", "Solid.js", "Tailwind CSS", "e-Commerce"],
        },
        {
          title: "Online Course Platform",
          description:
            "A content-protected site with login, server-side rendered (SSR) with Astro for a dynamic and secure user experience.",
          imageUrl:
            "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80",
          projectUrl: "#",
          tags: ["Astro", "React", "SSR", "Authentication"],
        },
        {
          title: "SaaS Landing Page",
          description:
            "A landing page with interactive islands for forms and dynamic components, achieving a First Contentful Paint under 1 second.",
          imageUrl:
            "https://images.unsplash.com/photo-1522199755839-a2bacb67c546?w=800&q=80",
          projectUrl: "#",
          tags: ["Astro", "Vue", "Animations", "Marketing"],
        },
      ],
    },
    philosophy: {
      title: "Our Strategy: Technology and Marketing for Your Growth",
      subtitle:
        "We merge technology and marketing into a unified system, focused on a single goal: accelerating your business growth.",
      card1_title: "Custom Software Development",
      card1_text:
        "We build the technological foundation your business needs. From web and mobile applications to process automation, we create a solid, secure, and scalable digital infrastructure.",
      card2_title: "Data-Driven Digital Marketing",
      card2_text:
        "We use the data generated by your technology to design effective marketing strategies. Through SEO, SEM, and valuable content, we attract your target audience and turn them into loyal customers.",
    },
    services: {
      title: "Services Designed to Scale Your Business",
      cards: [
        {
          iconName:
            "streamline:programming-browser-code-2-code-browser-tags-angle-programming-bracket",
          title: "Custom Web & App Development",
          description:
            "We create custom web platforms, e-commerce sites, and mobile apps focused on performance, technical SEO, and an exceptional user experience to convert visitors into customers.",
        },
        {
          iconName:
            "streamline:programming-browser-dashboard-app-code-apps-programming-window-dashboard-performance",
          title: "Process Automation & Systems Integration",
          description:
            "We eliminate repetitive tasks by integrating your tools via APIs and automating workflows (RPA). We optimize your operational efficiency so your team can focus on growth.",
        },
        {
          iconName:
            "streamline:money-graph-bar-increase-up-product-performance-increase-arrow-graph-business-chart",
          title: "SEO & Content Marketing",
          description:
            "We attract your ideal audience through technical audits, valuable content creation (articles, guides), and link-building strategies that position you as a leader in your industry.",
        },
        {
          iconName:
            "streamline:image-flash-1-flash-power-connect-charge-electricity-lightning",
          title: "Digital Advertising (PPC) & Social Media",
          description:
            "We manage your campaigns on Google Ads & Meta Ads (PPC), social media, and email marketing. We use a data-driven approach to maximize your return on investment (ROI).",
        },
      ],
    },
    process: {
      title: "Our Methodology: From Strategy to Results",
      steps: [
        {
          title: "Discovery & Strategy",
          description:
            "We conduct a comprehensive audit of your business to understand your goals, challenges, and competition. We define KPIs and create a strategic roadmap for success.",
        },
        {
          title: "Design & Prototyping",
          description:
            "We design the information architecture and create UX/UI prototypes. This ensures the final solution is intuitive, user-centric, and perfectly aligned with your brand.",
        },
        {
          title: "Agile Development & Implementation",
          description:
            "Using agile methodologies, our team builds your solution with clean, scalable code. In parallel, we implement the on-page SEO and prepare marketing campaigns for launch.",
        },
        {
          title: "Analysis & Continuous Growth",
          description:
            "Launch is just the beginning. We monitor performance through data analytics, conduct A/B testing, and continuously iterate to ensure we maximize your return on investment (ROI).",
        },
      ],
    },
    faq: {
      title: "Frequently Asked Questions",
      subtitle: "Key information to start your project with confidence.",
      items: [
        {
          question: "What is your work process like?",
          answer:
            "Our methodology is based on 4 phases: Discovery, Design, Agile Development, and Continuous Growth. This approach ensures that every solution is aligned with your KPIs and maximizes ROI.",
        },
        {
          question: "How much does a project cost?",
          answer:
            "We don't have fixed rates, as each project is unique. After a discovery session, we create a custom quote based on the scope and objectives, ensuring your investment generates maximum value.",
        },
        {
          question: "Do you work with startups and small businesses?",
          answer:
            "Absolutely! We specialize in helping startups and SMEs build a solid technological foundation. We can start with a Minimum Viable Product (MVP) and scale from there, adapting to your budget and growth pace.",
        },
        {
          question: "Do you offer support after launch?",
          answer:
            "Yes, we see the launch as the beginning of our partnership. We offer support and evolutionary maintenance plans that include updates, security monitoring, and continuous optimization to ensure long-term performance.",
        },
      ],
    },
    contactForm: {
      titlePart1: "Have an idea? ",
      titlePart2: "Let's talk.",
      subtitle:
        "I'm ready to help you automate processes, launch your next e-commerce store, or build the web application your business needs. Fill out the form, and I'll get in touch with you.",
      nameLabel: "Name",
      namePlaceholder: "Your full name",
      emailLabel: "Email",
      emailPlaceholder: "you@email.com",
      ideaLabel: "Project Idea",
      ideaPlaceholder:
        "Describe your project, your goals, or the problem you want to solve...",
      submitButton: "Send Message",
    },
    cta: {
      title: "Ready to Turn Your Idea into a Real Project?",
      subtitle:
        "Schedule a free strategic session with us and discover how the right technology and marketing can drive your business results.",
      ctaButton: "Schedule Free Session",
    },
    thanksPage: {
      title: "Thank You",
      exclamationMark: "!",
      subtitle:
        "We have received your message. We will get in touch with you very soon.",
      buttonText: "Back to Home",
    },
  },
  es: {
    nav: {
      philosophy: "Filosofía",
      services: "Servicios",
      process: "Nuestro Proceso",
      faq: "Preguntas Frecuentes",
      cta: "Contacto",
    },
    hero: {
      title: {
        prefix: "",
        highlight: "Impulsamos tu Crecimiento",
        suffix: " con Desarrollo y Marketing Digital",
      },
      subtitle:
        "Creamos soluciones de software a medida y estrategias de marketing que tu negocio necesita para escalar y triunfar en el mercado actual.",
      ctaButton: "Hablemos de tu Proyecto",
    },
    showcase: {
      title_prefix: "Nuestro ",
      title_highlight: "Trabajo",
      items: [
        {
          title: "E-commerce de Alto Rendimiento",
          description:
            "Una tienda en línea ultrarrápida construida con Astro, con cero JavaScript en el cliente por defecto para una carga instantánea y un SEO impecable.",
          imageUrl:
            "https://ix-marketing.imgix.net/case-study_tile_bentobox.png?auto=format,compress&w=1446",
          projectUrl: "#",
          tags: ["Astro", "Solid.js", "Tailwind CSS", "e-Commerce"],
        },
        {
          title: "Plataforma de Cursos en Línea",
          description:
            "Un sitio de contenido protegido con inicio de sesión, renderizado en el servidor (SSR) con Astro para una experiencia de usuario dinámica y segura.",
          imageUrl:
            "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80",
          projectUrl: "#",
          tags: ["Astro", "React", "SSR", "Autenticación"],
        },
        {
          title: "Landing Page para SaaS",
          description:
            "Página de aterrizaje con islas de interactividad para formularios y componentes dinámicos, logrando un First Contentful Paint por debajo de 1 segundo.",
          imageUrl:
            "https://images.unsplash.com/photo-1522199755839-a2bacb67c546?w=800&q=80",
          projectUrl: "#",
          tags: ["Astro", "Vue", "Animaciones", "Marketing"],
        },
      ],
    },
    philosophy: {
      title: "Nuestra Estrategia: Tecnología y Marketing para tu Crecimiento",
      subtitle:
        "Fusionamos tecnología y marketing en un sistema unificado, enfocado en un único objetivo: acelerar el crecimiento de tu negocio.",
      card1_title: "Desarrollo de Software a Medida",
      card1_text:
        "Construimos la base tecnológica que tu negocio necesita. Desde aplicaciones web y móviles hasta la automatización de procesos, creamos una infraestructura digital sólida, segura y preparada para escalar.",
      card2_title: "Marketing Digital Basado en Datos",
      card2_text:
        "Utilizamos los datos generados por tu tecnología para diseñar estrategias de marketing efectivas. A través de SEO, SEM y contenido de valor, atraemos a tu público objetivo y lo convertimos en clientes recurrentes.",
    },
    services: {
      title: "Servicios Diseñados para Escalar tu Negocio",
      cards: [
        {
          iconName:
            "streamline:programming-browser-code-2-code-browser-tags-angle-programming-bracket",
          title: "Desarrollo Web y Apps a Medida",
          description:
            "Creamos plataformas web, e-commerce y aplicaciones móviles a medida, enfocadas en el rendimiento, el SEO técnico y una experiencia de usuario excepcional para convertir visitantes en clientes.",
        },
        {
          iconName:
            "streamline:programming-browser-dashboard-app-code-apps-programming-window-dashboard-performance",
          title: "Automatización e Integración de Sistemas",
          description:
            "Eliminamos tareas repetitivas mediante la integración de tus herramientas vía APIs y la automatización de flujos de trabajo (RPA). Optimizamos tu eficiencia operativa para que tu equipo se centre en crecer.",
        },
        {
          iconName:
            "streamline:money-graph-bar-increase-up-product-performance-increase-arrow-graph-business-chart",
          title: "SEO y Marketing de Contenidos",
          description:
            "Atraemos a tu público ideal mediante auditorías técnicas, creación de contenido de valor (artículos, guías) y estrategias de link building que te posicionan como líder en tu sector.",
        },
        {
          iconName:
            "streamline:image-flash-1-flash-power-connect-charge-electricity-lightning",
          title: "Publicidad Digital (PPC) y Social Media",
          description:
            "Gestionamos tus campañas en Google Ads y Meta Ads (PPC), redes sociales y email marketing. Usamos un enfoque basado en datos para maximizar tu retorno de la inversión (ROI).",
        },
      ],
    },
    process: {
      title: "Nuestra Metodología: De la Estrategia a los Resultados",
      steps: [
        {
          title: "Descubrimiento y Estrategia",
          description:
            "Realizamos una auditoría completa de tu negocio para entender tus objetivos, desafíos y competencia. Definimos los KPIs y creamos un roadmap estratégico hacia el éxito.",
        },
        {
          title: "Diseño y Prototipado",
          description:
            "Diseñamos la arquitectura de la información y creamos prototipos de UX/UI. Así garantizamos que la solución final sea intuitiva, centrada en el usuario y alineada con tu marca.",
        },
        {
          title: "Desarrollo Ágil e Implementación",
          description:
            "Con metodologías ágiles, nuestro equipo construye tu solución con código limpio y escalable. En paralelo, implementamos el SEO on-page y preparamos las campañas de marketing.",
        },
        {
          title: "Análisis y Crecimiento Continuo",
          description:
            "El lanzamiento es solo el comienzo. Monitorizamos el rendimiento con analítica de datos, realizamos pruebas A/B e iteramos continuamente para garantizar el máximo retorno de la inversión (ROI).",
        },
      ],
    },
    faq: {
      title: "Preguntas Frecuentes",
      subtitle: "Información clave para empezar tu proyecto con confianza.",
      items: [
        {
          question: "¿Cuál es su proceso de trabajo?",
          answer:
            "Nuestra metodología se basa en 4 fases: Descubrimiento, Diseño, Desarrollo Ágil y Crecimiento Continuo. Este enfoque garantiza que cada solución esté alineada con sus KPIs y maximice el ROI.",
        },
        {
          question: "¿Cuánto cuesta un proyecto?",
          answer:
            "No tenemos tarifas fijas, ya que cada proyecto es único. Tras una sesión de descubrimiento, creamos un presupuesto a medida basado en el alcance y los objetivos, asegurando que su inversión genere el máximo valor.",
        },
        {
          question: "¿Trabajan con startups y PYMES?",
          answer:
            "¡Por supuesto! Nos especializamos en ayudar a startups y PYMES a construir una base tecnológica sólida. Podemos empezar con un Producto Mínimo Viable (MVP) y escalar desde ahí, adaptándonos a su presupuesto y ritmo de crecimiento.",
        },
        {
          question: "¿Ofrecen soporte después del lanzamiento?",
          answer:
            "Sí, consideramos el lanzamiento como el inicio de nuestra colaboración. Ofrecemos planes de soporte y mantenimiento evolutivo que incluyen actualizaciones, monitorización de seguridad y optimización continua para asegurar el rendimiento a largo plazo.",
        },
      ],
    },
    contactForm: {
      titlePart1: "¿Tienes una idea? ",
      titlePart2: "Hablemos.",
      subtitle:
        "Estoy listo para ayudarte a automatizar procesos, lanzar tu próximo e-commerce o construir la aplicación web que tu negocio necesita. Rellena el formulario y me pondré en contacto contigo.",
      nameLabel: "Nombre",
      namePlaceholder: "Tu nombre completo",
      emailLabel: "Email",
      emailPlaceholder: "tu@email.com",
      ideaLabel: "Idea a desarrollar",
      ideaPlaceholder:
        "Describe tu proyecto, tus objetivos o el problema que quieres resolver...",
      submitButton: "Enviar Mensaje",
    },
    cta: {
      title: "Convierte tu Idea en un Proyecto Real",
      subtitle:
        "Agenda una sesión estratégica gratuita y descubre cómo la tecnología y el marketing adecuados pueden impulsar los resultados de tu negocio.",
      ctaButton: "Agendar Sesión Gratuita",
    },
    thanksPage: {
      title: "Gracias",
      exclamationMark: "!",
      subtitle:
        "Hemos recibido tu mensaje. Nos pondremos en contacto contigo muy pronto.",
      buttonText: "Volver al Inicio",
    },
  },
  pt: {
    nav: {
      philosophy: "Filosofia",
      services: "Serviços",
      process: "Nosso Processo",
      faq: "Perguntas Frequentes",
      cta: "Contate-nos",
    },
    hero: {
      title: {
        prefix: "",
        highlight: "Impulsionamos",
        suffix: " o seu Crescimento com Desenvolvimento e Marketing Digital",
      },
      subtitle:
        "Criamos soluções de software à medida e estratégias de marketing que o seu negócio precisa para escalar e ter sucesso no mercado atual.",
      ctaButton: "Vamos Falar do seu Projeto",
    },
    showcase: {
      title_prefix: "O Nosso ",
      title_highlight: "Trabalho",
      items: [
        {
          title: "E-commerce de Alto Desempenho",
          description:
            "Uma loja online ultrarrápida construída com Astro, com zero JavaScript no cliente por defeito para um carregamento instantâneo e um SEO impecável.",
          imageUrl:
            "https://ix-marketing.imgix.net/case-study_tile_bentobox.png?auto=format,compress&w=1446",
          projectUrl: "#",
          tags: ["Astro", "Solid.js", "Tailwind CSS", "e-Commerce"],
        },
        {
          title: "Plataforma de Cursos Online",
          description:
            "Um site de conteúdo protegido com início de sessão, renderizado no servidor (SSR) com Astro para uma experiência de utilizador dinâmica e segura.",
          imageUrl:
            "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80",
          projectUrl: "#",
          tags: ["Astro", "React", "SSR", "Autenticação"],
        },
        {
          title: "Landing Page para SaaS",
          description:
            "Página de aterragem com ilhas de interatividade para formulários e componentes dinâmicos, alcançando um First Contentful Paint abaixo de 1 segundo.",
          imageUrl:
            "https://images.unsplash.com/photo-1522199755839-a2bacb67c546?w=800&q=80",
          projectUrl: "#",
          tags: ["Astro", "Vue", "Animações", "Marketing"],
        },
      ],
    },
    philosophy: {
      title:
        "A Nossa Estratégia: Tecnologia e Marketing para o seu Crescimento",
      subtitle:
        "Fundimos tecnologia e marketing num sistema unificado, focado num único objetivo: acelerar o crescimento do seu negócio.",
      card1_title: "Desenvolvimento de Software à Medida",
      card1_text:
        "Construímos a base tecnológica de que o seu negócio necessita. Desde aplicações web e móveis à automatização de processos, criamos uma infraestrutura digital sólida, segura e preparada para escalar.",
      card2_title: "Marketing Digital Baseado em Dados",
      card2_text:
        "Utilizamos os dados gerados pela sua tecnologia para desenhar estratégias de marketing eficazes. Através de SEO, SEM e conteúdo de valor, atraímos o seu público-alvo e convertemo-lo em clientes recorrentes.",
    },
    services: {
      title: "Serviços Desenhados para Escalar o seu Negócio",
      cards: [
        {
          iconName:
            "streamline:programming-browser-code-2-code-browser-tags-angle-programming-bracket",
          title: "Desenvolvimento Web e de Apps à Medida",
          description:
            "Criamos plataformas web, e-commerce e aplicações móveis à medida, focadas no desempenho, SEO técnico e numa experiência de utilizador excecional para converter visitantes em clientes.",
        },
        {
          iconName:
            "streamline:programming-browser-dashboard-app-code-apps-programming-window-dashboard-performance",
          title: "Automação e Integração de Sistemas",
          description:
            "Eliminamos tarefas repetitivas através da integração das suas ferramentas via APIs e da automação de fluxos de trabalho (RPA). Otimizamos a sua eficiência operacional para que a sua equipa se foque no crescimento.",
        },
        {
          iconName:
            "streamline:money-graph-bar-increase-up-product-performance-increase-arrow-graph-business-chart",
          title: "SEO e Marketing de Conteúdos",
          description:
            "Atraímos o seu público ideal através de auditorias técnicas, criação de conteúdo de valor (artigos, guias) e estratégias de link building que o posicionam como líder no seu setor.",
        },
        {
          iconName:
            "streamline:image-flash-1-flash-power-connect-charge-electricity-lightning",
          title: "Publicidade Digital (PPC) e Redes Sociais",
          description:
            "Gerimos as suas campanhas no Google Ads e Meta Ads (PPC), redes sociais e email marketing. Usamos uma abordagem baseada em dados para maximizar o seu retorno do investimento (ROI).",
        },
      ],
    },
    process: {
      title: "A Nossa Metodologia: Da Estratégia aos Resultados",
      steps: [
        {
          title: "Descoberta e Estratégia",
          description:
            "Realizamos uma auditoria completa do seu negócio para entender os seus objetivos, desafios e concorrência. Definimos os KPIs e criamos um roadmap estratégico para o sucesso.",
        },
        {
          title: "Design e Prototipagem",
          description:
            "Desenhamos a arquitetura da informação e criamos protótipos de UX/UI. Assim, garantimos que a solução final seja intuitiva, centrada no utilizador e alinhada com a sua marca.",
        },
        {
          title: "Desenvolvimento Ágil e Implementação",
          description:
            "Com metodologias ágeis, a nossa equipa constrói a sua solução com código limpo e escalável. Em paralelo, implementamos o SEO on-page e preparamos as campanhas de marketing.",
        },
        {
          title: "Análise e Crescimento Contínuo",
          description:
            "O lançamento é apenas o começo. Monitorizamos o desempenho com análise de dados, realizamos testes A/B e iteramos continuamente para garantir o máximo retorno do investimento (ROI).",
        },
      ],
    },
    faq: {
      title: "Perguntas Frequentes",
      subtitle:
        "Informação essencial para iniciar o seu projeto com confiança.",
      items: [
        {
          question: "Qual é o vosso processo de trabalho?",
          answer:
            "A nossa metodologia baseia-se em 4 fases: Descoberta, Design, Desenvolvimento Ágil e Crescimento Contínuo. Esta abordagem garante que cada solução esteja alinhada com os seus KPIs e maximize o ROI.",
        },
        {
          question: "Quanto custa um projeto?",
          answer:
            "Não temos preços fixos, pois cada projeto é único. Após uma sessão de descoberta, criamos um orçamento à medida com base no âmbito e nos objetivos, garantindo que o seu investimento gera o máximo valor.",
        },
        {
          question: "Trabalham com startups e PMEs?",
          answer:
            "Com certeza! Somos especialistas em ajudar startups e PMEs a construir uma base tecnológica sólida. Podemos começar com um Produto Mínimo Viável (MVP) e escalar a partir daí, adaptando-nos ao seu orçamento e ritmo de crescimento.",
        },
        {
          question: "Oferecem suporte após o lançamento?",
          answer:
            "Sim, consideramos o lançamento como o início da nossa parceria. Oferecemos planos de suporte e manutenção evolutiva que incluem atualizações, monitorização de segurança e otimização contínua para garantir o desempenho a longo prazo.",
        },
      ],
    },
    contactForm: {
      titlePart1: "Tem uma ideia? ",
      titlePart2: "Vamos conversar.",
      subtitle:
        "Estou pronto para o ajudar a automatizar processos, lançar a sua próxima loja de e-commerce ou construir a aplicação web que o seu negócio precisa. Preencha o formulário e entrarei em contacto consigo.",
      nameLabel: "Nome",
      namePlaceholder: "O seu nome completo",
      emailLabel: "Email",
      emailPlaceholder: "o.seu@email.com",
      ideaLabel: "Ideia do Projeto",
      ideaPlaceholder:
        "Descreva o seu projeto, os seus objetivos ou o problema que pretende resolver...",
      submitButton: "Enviar Mensagem",
    },
    cta: {
      title: "Transforme a sua Ideia num Projeto Real",
      subtitle:
        "Agende uma sessão estratégica gratuita connosco e descubra como a tecnologia e o marketing certos podem impulsionar os resultados do seu negócio.",
      ctaButton: "Agendar Sessão Gratuita",
    },
    thanksPage: {
      title: "Obrigado",
      exclamationMark: "!",
      subtitle:
        "Recebemos a sua mensagem. Entraremos em contacto consigo em breve.",
      buttonText: "Voltar ao Início",
    },
  },
};
