export const translationsScheduler = {
  es: {
    pricePlanAnnual: "Anual",
    pricePlanMonthly: "Mensual",
    billingCycleMonthly: "/mes",
    priceNoteAnnual: "Facturado como 600.00 € al año",
    priceNoteMonthly: "Pago flexible, cancela cuando quieras",
    calendarLocale: "es-ES",
    step1Title: "1. Selecciona un Día y Hora",
    step2Title: "2. Confirma y Paga",
    availableSlotsTitle: "Horarios Disponibles",
    noSlots: "No hay horarios disponibles para este día.",
    summaryTitle: "Resumen de la Consulta",
    summaryDate: "Fecha:",
    summaryTime: "Hora:",
    summaryPlan: "Plan:",
    summaryPrice: "Precio:",
    payButton: "Pagar y Confirmar Cita",
    payProcessing: "Procesando...",
    paymentInfo: "🔒 Pago seguro a través de nuestro proveedor.",
    confirmationTitle: "¡Cita y Pago Confirmados!",
    confirmationDate: "Has agendado tu consulta para el",
    confirmationTime: "La hora de la cita es a las",
    confirmationEmail:
      "Recibirás un email con el enlace de la videollamada y todos los detalles. ¡Nos vemos pronto!",
  },
  en: {
    pricePlanAnnual: "Annual",
    pricePlanMonthly: "Monthly",
    billingCycleMonthly: "/month",
    priceNoteAnnual: "Billed as 600.00 € per year",
    priceNoteMonthly: "Flexible payment, cancel anytime",
    calendarLocale: "en-US",
    step1Title: "1. Select a Day and Time",
    step2Title: "2. Confirm and Pay",
    availableSlotsTitle: "Available Time Slots",
    noSlots: "No available time slots for this day.",
    summaryTitle: "Consultation Summary",
    summaryDate: "Date:",
    summaryTime: "Time:",
    summaryPlan: "Plan:",
    summaryPrice: "Price:",
    payButton: "Pay and Confirm Appointment",
    payProcessing: "Processing...",
    paymentInfo: "🔒 Secure payment through our provider.",
    confirmationTitle: "Appointment and Payment Confirmed!",
    confirmationDate: "You have scheduled your consultation for",
    confirmationTime: "The appointment time is at",
    confirmationEmail:
      "You will receive an email with the video call link and all the details. See you soon!",
  },
  pt: {
    pricePlanAnnual: "Anual",
    pricePlanMonthly: "Mensal",
    billingCycleMonthly: "/mês",
    priceNoteAnnual: "Cobrado como 600,00 € por ano",
    priceNoteMonthly: "Pagamento flexível, cancele quando quiser",
    calendarLocale: "pt-PT",
    step1Title: "1. Selecione um Dia e Hora",
    step2Title: "2. Confirme e Pague",
    availableSlotsTitle: "Horários Disponíveis",
    noSlots: "Não há horários disponíveis para este dia.",
    summaryTitle: "Resumo da Consulta",
    summaryDate: "Data:",
    summaryTime: "Hora:",
    summaryPlan: "Plano:",
    summaryPrice: "Preço:",
    payButton: "Pagar e Confirmar Consulta",
    payProcessing: "Processando...",
    paymentInfo: "🔒 Pagamento seguro através do nosso provedor.",
    confirmationTitle: "Consulta e Pagamento Confirmados!",
    confirmationDate: "Você agendou sua consulta para",
    confirmationTime: "O horário da consulta é às",
    confirmationEmail:
      "Você receberá um e-mail com o link da videochamada e todos os detalhes. Até breve!",
  },
};
