export const translationsScheduler = {
  es: {
    title: "Estás a un Paso de Empezar",
    subtitle:
      "Asegura tu espacio para la consulta inicial. Aquí definiremos la estrategia para tu proyecto.",
    selectDate: "1. Selecciona un Día y Hora",
    availableSlots: "Horarios Disponibles",
    timezoneInfo: "Horarios en tu zona horaria",
    noSlots: "No hay horarios disponibles para este día.",
    confirmPay: "2. Confirma y Paga",
    summary: "Resumen de la Consulta",
    date: "Fecha:",
    hour: "Hora:",
    plan: "Plan:",
    price: "Precio:",
    payBtn: "Pagar y Confirmar Cita",
    processing: "Procesando...",
    paymentInfo: "🔒 Pago seguro a través de nuestro proveedor.",
    paidTitle: "¡Cita y Pago Confirmados!",
    paidDate: "Has agendado tu consulta para el",
    paidHour: "La hora de la cita es a las",
    paidSpain: "(Hora de España)",
    paidClient: "(Tu Hora Local)",
    paidEmail:
      "Recibirás un email con el enlace de la videollamada y todos los detalles. ¡Nos vemos pronto!",
    selectDay: "Selecciona un día",
    selectHour: "Selecciona un horario",
    planAnual: "Anual",
    planMensual: "Mensual",
    priceAnual: "$50.00 USD",
    priceMensual: "$99.00 USD",
    billingCycle: "/mes",
    noteAnual: "Facturado como $600.00 al año",
    noteMensual: "Pago flexible, cancela cuando quieras",
  },
  en: {
    title: "You're One Step Away",
    subtitle:
      "Secure your spot for the initial consultation. Here we'll define the strategy for your project.",
    selectDate: "1. Select a Day and Time",
    availableSlots: "Available Time Slots",
    timezoneInfo: "Times in your time zone",
    noSlots: "No available slots for this day.",
    confirmPay: "2. Confirm and Pay",
    summary: "Consultation Summary",
    date: "Date:",
    hour: "Time:",
    plan: "Plan:",
    price: "Price:",
    payBtn: "Pay and Confirm Appointment",
    processing: "Processing...",
    paymentInfo: "🔒 Secure payment via our provider.",
    paidTitle: "Appointment and Payment Confirmed!",
    paidDate: "You have scheduled your consultation for",
    paidHour: "The appointment time is at",
    paidSpain: "(Spain Time)",
    paidClient: "(Your Local Time)",
    paidEmail:
      "You will receive an email with the video call link and all details. See you soon!",
    selectDay: "Select a day",
    selectHour: "Select a time slot",
    planAnual: "Annual",
    planMensual: "Monthly",
    priceAnual: "$50.00 USD",
    priceMensual: "$99.00 USD",
    billingCycle: "/month",
    noteAnual: "Billed as $600.00 per year",
    noteMensual: "Flexible payment, cancel anytime",
  },
  pt: {
    title: "Está a um Passo de Começar",
    subtitle:
      "Garanta o seu lugar para a consulta inicial. Aqui definiremos a estratégia para o seu projeto.",
    selectDate: "1. Selecione um Dia e Hora",
    availableSlots: "Horários Disponíveis",
    timezoneInfo: "Horários no seu fuso horário",
    noSlots: "Não há horários disponíveis para este dia.",
    confirmPay: "2. Confirme e Pague",
    summary: "Resumo da Consulta",
    date: "Data:",
    hour: "Hora:",
    plan: "Plano:",
    price: "Preço:",
    payBtn: "Pagar e Confirmar Consulta",
    processing: "A processar...",
    paymentInfo: "🔒 Pagamento seguro através do nosso fornecedor.",
    paidTitle: "Consulta e Pagamento Confirmados!",
    paidDate: "Agendou a sua consulta para",
    paidHour: "A hora da consulta é às",
    paidSpain: "(Hora de Espanha)",
    paidClient: "(Sua Hora Local)",
    paidEmail:
      "Receberá um email com o link da videochamada e todos os detalhes. Até breve!",
    selectDay: "Selecione um dia",
    selectHour: "Selecione um horário",
    planAnual: "Anual",
    planMensual: "Mensal",
    priceAnual: "$50.00 USD",
    priceMensual: "$99.00 USD",
    billingCycle: "/mês",
    noteAnual: "Faturado como $600.00 por ano",
    noteMensual: "Pagamento flexível, cancele quando quiser",
  },
};
